version: "3"

networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:3.2.3'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    healthcheck:
      test: "kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1"
      interval: 2s
      timeout: 2s
      retries: 15
    networks:
      - app-tier

  app:
    build: .
    working_dir: /home/appuser
    command: faust -A teste worker -l info
    volumes:
      - ./src/:/home/appuser
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-tier
